Feat: Map and Footer Added
TechnicalTeam-BVCOENM/Abhiyaan-website pull request #3
Opened 2024-01-13 15:08 UTC by Rushi67

2024-01-15 04:26 UTC, psantosh16 commented
Make suggested changes , drop a message

2024-01-15 04:28 UTC, psantosh16 requested changes
Make suggested changes , drop a message

2024-01-15 10:12 UTC, Rushi67 commented
Done

2024-01-15 10:37 UTC, psantosh16 requested changes

2024-01-15 10:37 UTC, psantosh16 commented on src/components/footer/footer.jsx
Extract the Icons List from main footer file and make another file for that in root footer folder.

Maintain clean code

2024-01-15 11:18 UTC, Rushi67 commented on src/components/footer/footer.jsx
done

2024-01-16 16:17 UTC, psantosh16 approved these changes

2024-01-16 16:18 UTC, merged