sponsors page made responsive
TechnicalTeam-BVCOENM/Abhiyaan-website pull request #4
Opened 2024-01-14 13:21 UTC by sambhavnrana

2024-01-15 04:27 UTC, psantosh16 commented
Don't make duplicate PR's. And delete which ever is not needed

2024-01-15 04:28 UTC, psantosh16 requested changes
Kindly delete previous unmergerd PRs SambhavJii

2024-01-15 10:31 UTC, psantosh16 commented on src/components/sponsors/sponsors.jsx
Use NextJs  <Image> component

2024-01-15 10:34 UTC, psantosh16 requested changes
Changes are needed

2024-01-15 10:34 UTC, psantosh16 commented on src/components/sponsors/sponsors.jsx
Use Image from NEXTJS instead of img

👍 Nice work in maintaining clean code

2024-01-15 10:34 UTC, psantosh16 commented on src/app/page.jsx
Import SponsorsPage from sponsors instead of content

2024-01-15 10:47 UTC, sambhavnrana commented
> Don't make duplicate PR's. And delete which ever is not needed

Okay

2024-01-16 16:14 UTC, psantosh16 approved these changes

2024-01-16 16:21 UTC, psantosh16 approved these changes

2024-01-16 16:24 UTC, psantosh16 approved these changes

2024-01-16 16:27 UTC, psantosh16 approved these changes

2024-01-16 16:39 UTC, merged